### ISSUE TITLE
M13ProgressViewSegmentedRing - secondary color

### ISSUE THREAD

**Issue by pejn** [Marxon13/M13ProgressSuite#105]
There's a problem with setting secondaryColor for Segmented Ring. 
![zrzut ekranu 2016-09-18 o 17 18 14](https://cloud.githubusercontent.com/assets/5834738/18616865/f9fb7e26-7dc3-11e6-8dac-83f294d3aa65.png)
Code used by me:
progressView.showPercentage = false
progressView.numberOfSegments = 30
progressView.progressRingWidth = 9
progressView.primaryColor = UIColor(white: 1, alpha: 0.4)
progressView.secondaryColor = UIColor.whiteColor()

**Comment by jaredtaskin** [comment]
I'm experiencing a similar issue with M13ProgressViewRing. Secondary color seems to have broken in Xcode 8/iOS 10

**Comment by jaredtaskin** [comment]
I have solved my issue. It had to do with backgroundRingWidth. I believe the default value is calculated based on self.bounds, and this might be causing a problem in iOS 10. Setting backgroundRingWidth = 1 solved my problem.
