### ISSUE TITLE
the indeterminate animation stopped when app enter background and back to foreground

### ISSUE THREAD

**Issue by supwy** [Marxon13/M13ProgressSuite#17]
set progress ring view to indeterminate mode and let app enter background and back to foreground. the indeterminate animation stopped.

**Comment by claudiumatei** [comment]
@maiconpeixinho, check my answer from issue #53 
It seems that setting again the property "indeterminate" of the progress view will reset the animation. Something like: 
`self.progressView.indeterminate = self.progressView.indeterminate;`

**Comment by maiconpeixinho** [comment]
Nice workaround @claudiumatei! Thank you..
