### ISSUE TITLE
<Error>: CGContextDrawRadialGradient: invalid context 0x0

### ISSUE THREAD

**Issue by marcoancona** [Marxon13/M13ProgressSuite#35]
M13ProgressHUD with mask M13ProgressHUDMaskTypeGradient generates the following warning:

>Error: CGContextDrawRadialGradient: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by jurysch** [comment]
Seems this issue can be closed now then, right?

**Comment by fform** [comment]
I'm using 1.2.7 and I still see this issue

**Comment by hpwooten** [comment]
It's also happening in the drawMask method in M13ProgressHUD

**Comment by Marxon13** [comment]
I think I fixed the issue, if not I'll re-open this one.
