### ISSUE TITLE
M13ProgressViewRing stops spinning

### ISSUE THREAD

**Issue by matthewmoss** [Marxon13/M13ProgressSuite#37]
Hello, I am trying to use a the M13ProgressViewRing without showing the percentage, but sometimes the the progress ring isn't spinning, it is just frozen in one spot.

**Comment by pavankataria** [comment]
I'm getting this same issue but this happens on my cells when I pop back onto the view controller the cell's spinning indicators stop spinning. I'm not hiding any table views here.
