### ISSUE TITLE
M13ProgressViewBar animation stops after coming back to app from background

### ISSUE THREAD

**Issue by zdenektopic** [Marxon13/M13ProgressSuite#53]
I have read #17 but theres no "animated" property on M13ProgressViewBar class

**Comment by claudiumatei** [comment]
I found the same problem, and I will add here a "fix" for it: When you get UIApplicationWillEnterForegroundNotification notification simply set again the property "indeterminate" of the progress view. It seems that this will restart the animation.

So, I did something like this and it works like a charm:
self.progressView.indeterminate = self.progressView.indeterminate;
