### ISSUE TITLE
Segmented Ring Color

### ISSUE THREAD

**Issue by bport95** [Marxon13/M13ProgressSuite#62]
Hello, I am trying to change the color of the rings that are already filled in on the segmented ring color.
Here is the code I have but it doesn't seem to be doing the job: 

    UIColor *theColor = [UIColor colorWithRed:25/255.0 green:197/255.0 blue:255/255.0 alpha:1.0];
    [_progressView setTintColor:theColor];

Any suggestions?

**Comment by benjerrim** [comment]
Just tried to do this myself and found this bug. I've updated the source code to fix it and will commit shortly.
