### ISSUE TITLE
M13ProgressViewRing  setProgress: animated: does not work

### ISSUE THREAD

**Issue by WuKongCoo1** [Marxon13/M13ProgressSuite#73]
First of all, I'm sorry, my English is very bad.  When I created the download task, using this method does not work. Only when the download is complete, the UI will change. Thank you

**Comment by Jauzee** [comment]
@WuKongCoo1 You must update the progress in main queue, like this (Swift):
dispatch_async(dispatch_get_main_queue(), {
self.navigationController?.setProgress(myProgress, animated: true)
}
